#!/usr/bin/env node
const readline = require('readline');

if (process.argv.length < 5) {
  console.log('Usage: ndjson-merge <prefix> <separator> <suffix>')
  process.exit(1);
}

var prefix = process.argv[2];
var separator = process.argv[3];
var suffix = process.argv[4];

process.stdout.write(prefix);
var count = 0;
readline.createInterface({
  input: process.stdin,
  output: null,
}).on('line', function(line) {
  if (count++ > 0) {
    process.stdout.write(separator);
  }
  process.stdout.write(line);
}).on('close', function() {
  process.stdout.write(suffix);
}).on('error', (err) => {
  console.error(err);
  process.exit(1);
});
